# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CPAN-Site
version:      0.15
version_from: 
installdirs:  site
requires:
    Test::More:                    0.5
    Test::Pod:                     1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
